### ISSUE TITLE
Regarding README point 8

### ISSUE THREAD

**Issue by Anatoly03** [JohannesStoehr/gad23-tests#12]
> 8. **Do not add the tests/modified build.gradle to your artemis git repository** (it should already be in your .gitignore)

`build.gradle` is a tracked file and cannot be ignored from git, I think it's important to state 'when possible' or 'not to push', alternatively, mention 'how to stage commits'

Tracked files [can only be removed from git history](https://stackoverflow.com/questions/1274057/how-do-i-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore). Not sure how it would affect the Artemis repository.

**Comment by JohannesStoehr** [comment]
It's not even in the .gitignore...
I just copied that point from @MaximilianAnzinger 😅
