### ISSUE TITLE
Setting the default merge option to 'Squash Commits: PR Titel + Description'

### ISSUE THREAD

**Issue by nilsreichardt** [JohannesStoehr/gad23-tests#13]
![image](https://user-images.githubusercontent.com/24459435/233381484-f070364a-2cb5-43bf-9663-bad7ea6e4f4b.png)

@JohannesStoehr Would it be possible to set the default merge option to ''Squash Commits: PR Titel + Description". This would help us to get a clean commit history on the `main` branch. Otherwise there will be all the commits of the PR on the `main` branch.

**Comment by JohannesStoehr** [comment]
Done
